src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[ORM\Column(type: 'string', length: 255)]
    private $Username;

    #[ORM\Column(type: 'string', length: 255)]
    private $Last_name;

    #[ORM\Column(type: 'integer')]
    private $phone;

    #[ORM\Column(type: 'string', length: 255)]
    private $Adresse;

    #[ORM\OneToMany(mappedBy: 'idClient', targetEntity: Command::class)]
    private $commands;

    public function __construct()
    {
        $this->commands = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->Last_name;
    }

    public function setLastName(string $Last_name): self
    {
        $this->Last_name = $Last_name;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
	/**
	 * @return mixed
	 */
	function getUsername() {
        return $this->Username;
    }

    function getFullName() {
        return $this->Username . " " . $this->Last_name;
    }
     /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    // public function getUsername(): string
    // {
    //     return (string) $this->email;
    // }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    /**
     * @return Collection<int, Command>
     */
    public function getCommands(): Collection
    {
        return $this->commands;
    }

    public function addCommand(Command $command): self
    {
        if (!$this->commands->contains($command)) {
            $this->commands[] = $command;
            $command->setIdClient($this);
        }

        return $this;
    }

    public function removeCommand(Command $command): self
    {
        if ($this->commands->removeElement($command)) {
            // set the owning side to null (unless already changed)
            if ($command->getIdClient() === $this) {
                $command->setIdClient(null);
            }
        }

        return $this;
    }
    public function __toString() {
        return $this->Username;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use ContainerM7CPF6T\getUser2Service;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use App\Repository\UserRepository;
use App\Entity\User;

#[Route('/profil')]

class ProfilController extends AbstractController
{
    #[Route('/index', name: 'app_profil')]
    public function index(): Response
    {
        if (!$this->getUser()){
            return $this->redirectToRoute('dashboard');
        }

        return $this->render('profil/index.html.twig', [
            'user' => $this->getUser(),
        ]);
    }

    public function Form(Request $request, UserRepository $UserRepository): Response
    {
        $User = new User();
        $form = $this->createForm(UsersType::class, $User);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $UserRepository->add($User, true);

            return $this->redirectToRoute('app_Users_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('Users_crud/new.html.twig', [
            'User' => $User,
            'form' => $form,
        ]);
    }

    #[Route('/update/image', name: 'upload_image')]
    public function UpdateProfilImage(Request $request,FlashBagInterface $flashMessage)
    {
        $image = $request->files->get("image");
        $image_name = $image->getClientOriginalName();
        $image->move($this->getParameter("image_directory"), $image_name);
        $user = $this->getUser();
        $user->setImage($image_name);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->flush();
        $flashMessage->add("seccess", "Profil modifié !");
        return $this->redirectToRoute('app_profil');
    }

    // public function UpdateCoverImage(Request $request,FlashBagInterface $flashMessage)
    // {
    //     $image = $request->files->get("image");
    //     $image_name = $image->getClientOriginalName();
    //     $image->move($this->getParameter("image_directory"), $image_name);
    //     $user = $this->getUser();
    //     $user->setImage($image_name);
    //     $entityManager = $this->getDoctrine()->getManager();
    //     $entityManager->persist($user);
    //     $entityManager->flush();
    //     $flashMessage->add("seccess", "Coverture modifié !");
    //     return $this->redirectToRoute('app_profil');
    // }
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profil{% endblock %}

{% block body %}
<div class="card">
							<div class="card-body bg-blue text-center card-img-top" style="background-image: url(/background-blue.jpg); height:350px">
								<div class="card-img-actions d-inline-block mb-3">
								{% if user.image == null %}
						 			{# Profil image Par défaut: #}
										{# <img src="/profil-image.jpg" class="border-white rounded-circle" width="48" height="48" alt=""> #}
										<img class="img-fluid rounded-circle" src="/Dont_Have_Image.png" style="width:170px; height:170px; margin-top:50px" alt="">

									</a>

								{% else %}
									{# Profil image : #}
									
										<img class="img-fluid rounded-circle" src="{{asset('/uploads/'~app.user.image)}}" style="width:170px; height:170px; margin-top:50px" alt="">
									</a>
								{% endif %}

									<div class="card-img-actions-overlay card-img rounded-circle" style="width:170px; height:170px;margin-top:50px">
										<a href="#" class="btn btn-outline bg-white text-white border-white border-2 btn-icon rounded-round">

                                        <form  action="{{path('upload_image')}}" method="post" enctype="multipart/form-data" >
									        <i class="icon-plus3">
											<input type="file" class="form-control" name="image" id="image" >
											</i><br>
						 			        <button  style="margin-top:5px;" type="submit" name="" id="" class="btn btn-primary" btn-lg btn-block>Confirm</button>
								        </form>
										
										</a>
									</div>
								</div>

								<h4 class="font-weight-semibold mb-0">{{app.user.fullName}}</h4>
								<span class="d-block opacity-75">Admin</span>
							</div>

							<div class="card-body border-top-0">
								<h2>My Informations :</h2>
								<div class="d-sm-flex flex-sm-wrap mb-3" style="margin-top:30px">
									<div class="font-weight-semibold">First name:</div>
									<div class="ml-sm-auto mt-2 mt-sm-0">{{user.Username}}</div>
								</div>

								<div class="d-sm-flex flex-sm-wrap mb-3">
									<div class="font-weight-semibold">Last name:</div>
									<div class="ml-sm-auto mt-2 mt-sm-0">{{user.Lastname}}</div>
								</div>

								<div class="d-sm-flex flex-sm-wrap mb-3">
									<div class="font-weight-semibold">Phone number:</div>
									<div class="ml-sm-auto mt-2 mt-sm-0">{{user.Phone}}</div>
								</div>

								<div class="d-sm-flex flex-sm-wrap">
									<div class="font-weight-semibold">Personal Email:</div>
									<div class="ml-sm-auto mt-2 mt-sm-0"><a href="#">{{app.user.Email}}</a></div>
								</div>
							</div>
</div>

















{# <h2 style="margin-left:40%;color:blue">My Profil</h2> #}
<!-- Cover area -->
				{# <div class="profile-cover" style="margin-top:10px">
					Coverture image 
					
					<div class="profile-cover-img" style="background-image: url(/background-blue.jpg)"></div>
					<div class="media align-items-center text-center text-md-left flex-column flex-md-row m-0">
						<div class="mr-md-3 mb-2 mb-md-0">

						{% if user.image == null %}
						 	Profil image Par défaut:
							
								<img src="/profil-image.jpg" class="border-white rounded-circle" width="48" height="48" alt="">
							</a>

						{% else %}
							Profil image :
							<a href="#" class="profile-thumb">
								<img src="{{asset('/uploads/'~user.image)}}" class="border-white rounded-circle" width="48" height="48" alt="">
							</a>
						{% endif %}

						</div>
						<div style="margin-top:50px; color:white">
				    		<h1 class="mb-0" >{{ app.user.userIdentifier }}</h1>
				    		<span class="d-block">Admin</span>

							<div  style="margin-top:10px; ">
								<form  action="{{path('upload_image')}}" method="post" enctype="multipart/form-data">
									<input type="file" class="form-control" name="image" id="image" >
						 			<button  style="margin-top:5px;margin-left:-250px" type="submit" name="" id="" class="btn btn-primary" btn-lg btn-block>Valider</button>
								</form>
							</div>
						</div>
						
						<div class="ml-md-3 mt-2 mt-md-0">
							<ul class="list-inline list-inline-condensed mb-0">
                            	<li class="list-inline-item"><a href="#" class="btn btn-light border-transparent"><i class="icon-file-stats mr-2"></i> Profil image</a></li>
								<li style="margin-left:400px;margin-top:80px" class="list-inline-item"><a href="#" class="btn btn-light border-transparent"><i class="icon-file-picture mr-2"></i> Cover image</a></li>
							</ul>
						</div>
					</div>
				</div> #}
<!-- /cover area -->
				<!-- Basic layout-->
						{# <div class="card">
							<div class="card-header header-elements-inline">
								<h5 class="card-title">Your Informations</h5>
								<div class="header-elements">
									<div class="list-icons">
				                		<a class="list-icons-item" data-action="collapse"></a>
				                		<a class="list-icons-item" data-action="reload"></a>
				                		<a class="list-icons-item" data-action="remove"></a>
				                	</div>
			                	</div>
							</div>

							<div class="card-body">
								<form action="" method="post">
									<div class="form-group">
										<label>First Name</label>
										<input type="text" class="form-control" placeholder="First Name">
									</div>

									<div class="form-group">
										<label>Last Name</label>
										<input type="text" class="form-control" placeholder="Last Name">
									</div>

									<div class="form-group">
										<label>Phone</label>
										<input type="tel" class="form-control" placeholder="Your Phone">
									</div>

									<div class="text-right">
										<button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
									</div>
								</form>
							</div>
						</div> #}
						<!-- /basic layout -->
						
{% endblock %}