src/Entity/BricoleursPlatriers.php
<?php

namespace App\Entity;

use App\Repository\BricoleursPlatriersRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BricoleursPlatriersRepository::class)]
class BricoleursPlatriers
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Name;

    #[ORM\Column(type: 'string', length: 255)]
    private $Last_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $Phone;

    #[ORM\Column(type: 'string', length: 255)]
    private $Job;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->Last_name;
    }

    public function setLastName(string $Last_name): self
    {
        $this->Last_name = $Last_name;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->Job;
    }

    public function setJob(string $Job): self
    {
        $this->Job = $Job;

        return $this;
    }
	/**
	 * @return mixed
	 */
	function getPhone() {
		return $this->Phone;
	}
	
	/**
	 * @param mixed $Phone 
	 * @return BricoleursPlatriers
	 */
	function setPhone($Phone): self {
		$this->Phone = $Phone;
		return $this;
	}
}

src/Controller/DemenageursCrudController.php
<?php

namespace App\Controller;

use App\Entity\BricoleursDemenageurs;
use App\Form\BricoleursDemenageursType;
use App\Repository\BricoleursDemenageursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/demenageurs')]
class DemenageursCrudController extends AbstractController
{
    #[Route('/index', name: 'app_demenageurs_crud_index', methods: ['GET'])]
    public function index(BricoleursDemenageursRepository $bricoleursDemenageursRepository): Response
    {
        return $this->render('demenageurs_crud/index.html.twig', [
            'bricoleurs_demenageurs' => $bricoleursDemenageursRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_demenageurs_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BricoleursDemenageursRepository $bricoleursDemenageursRepository): Response
    {
        $bricoleursDemenageur = new BricoleursDemenageurs();
        $form = $this->createForm(BricoleursDemenageursType::class, $bricoleursDemenageur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bricoleursDemenageursRepository->add($bricoleursDemenageur, true);

            return $this->redirectToRoute('app_demenageurs_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('demenageurs_crud/new.html.twig', [
            'bricoleurs_demenageur' => $bricoleursDemenageur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_demenageurs_crud_show', methods: ['GET'])]
    public function show(BricoleursDemenageurs $bricoleursDemenageur): Response
    {
        return $this->render('demenageurs_crud/show.html.twig', [
            'bricoleurs_demenageur' => $bricoleursDemenageur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_demenageurs_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, BricoleursDemenageurs $bricoleursDemenageur, BricoleursDemenageursRepository $bricoleursDemenageursRepository): Response
    {
        $form = $this->createForm(BricoleursDemenageursType::class, $bricoleursDemenageur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bricoleursDemenageursRepository->add($bricoleursDemenageur, true);

            return $this->redirectToRoute('app_demenageurs_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('demenageurs_crud/edit.html.twig', [
            'bricoleurs_demenageur' => $bricoleursDemenageur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_demenageurs_crud_delete', methods: ['POST'])]
    public function delete(Request $request, BricoleursDemenageurs $bricoleursDemenageur, BricoleursDemenageursRepository $bricoleursDemenageursRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bricoleursDemenageur->getId(), $request->request->get('_token'))) {
            $bricoleursDemenageursRepository->remove($bricoleursDemenageur, true);
        }

        return $this->redirectToRoute('app_demenageurs_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/demenageurs_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_demenageurs_crud_delete', {'id': bricoleurs_demenageur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bricoleurs_demenageur.id) }}">

<button class="btn btn-danger" style="width:150px; margin-top:10px; margin-left:80px">Delete</button>

</form>

templates/demenageurs_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {# <button class="btn">{{ button_label|default('Save') }}</button> #}
        <button class="btn btn-primary" style="margin-left:80px;padding-left:50px;padding-right:60px;width:150px">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/demenageurs_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Demenageurs{% endblock %}

{% block body %}
    <div style="margin-left:30%; margin-top:20px; width:370px">
        <h2>Edit Le Demenageur " {{bricoleurs_demenageur.Name}} "</h2>
        {{ include('demenageurs_crud/_form.html.twig', {'button_label': 'Update'}) }}
        <a href="{{ path('app_demenageurs_crud_index') }}" class="btn btn-danger" style="width:150px; margin-top:10px; margin-left:80px">back to list</a>
        {{ include('demenageurs_crud/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/demenageurs_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demenageurs{% endblock %}

{% block body %}

            <div class="row">
					<div class="col-md-6" style="margin:40px">
						<!-- Minuisiers list -->
						<div class="card" style="width:1000px">
							<div class="card-header header-elements-inline">
                                <h5 class="card-title" style="color:blue">Les Demenageurs</h5>
								<div class="header-elements">
                                    <div class="list-icons">
				                		<a class="icon-plus-circle2" href="{{ path('app_demenageurs_crud_new') }}" ></a>
		                		        <a class="list-icons-item" style="color:blue" data-action="collapse"></a>
		                		        <a class="list-icons-item" style="color:blue" data-action="reload"></a>
		                		        <a class="list-icons-item" style="color:blue" data-action="remove"></a>
		                	        </div>
			                	</div>
							</div>
				<table class="table datatable-basic">
                    <thead>
                        <tr>
                            {# <th>Id</th> #}
                            <th>Name</th>
                            <th>Last_name</th>
                            <th>Phone</th>
                            <th>Job</th>
                            <th class="text-center">actions</th>
                        </tr>
                    </thead>
					<tbody>
					 {% for bricoleurs_demenageur in bricoleurs_demenageurs %}
                        <tr>
                            {# <td>{{ bricoleurs_demenageur.id }}</td> #}
                            <td>{{ bricoleurs_demenageur.Name }}</td>
                            <td>{{ bricoleurs_demenageur.LastName }}</td>
                            <td>{{ bricoleurs_demenageur.phone }}</td>
                            <td>{{ bricoleurs_demenageur.Job }}</td>
							<td class="text-center">
                                                <div class="list-icons">
													<div class="dropdown">
                                                            <a href="#" class="list-icons-item" data-toggle="dropdown"><i class="icon-stairs"></i></a>
                                                            <div class="dropdown-menu dropdown-menu-right">
                                                                <a href="{{ path('app_demenageurs_crud_show', {'id': bricoleurs_demenageur.id}) }}" class="dropdown-item"><i class="icon-eye"></i>Afficher</a>
                                                                <a href="{{ path('app_demenageurs_crud_edit', {'id': bricoleurs_demenageur.id}) }}" class="dropdown-item"><i class="icon-pencil5"></i>Modifier</a>
                                                                <a href="{{ path('app_demenageurs_crud_show', {'id': bricoleurs_demenageur.id}) }}" class="dropdown-item"><i class="icon-close2"></i>Supprimer</a>
                                                            </div>
													</div>
												</div>
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="5">no records found</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
						</div>
						<!-- /Minuisiers list -->
			</div>
    {# <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Last_name</th>
                <th>Phone</th>
                <th>Job</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for bricoleurs_demenageur in bricoleurs_demenageurs %}
            <tr>
                <td>{{ bricoleurs_demenageur.id }}</td>
                <td>{{ bricoleurs_demenageur.Name }}</td>
                <td>{{ bricoleurs_demenageur.LastName }}</td>
                <td>{{ bricoleurs_demenageur.phone }}</td>
                <td>{{ bricoleurs_demenageur.Job }}</td>
                <td>
                    <a href="{{ path('app_demenageurs_crud_show', {'id': bricoleurs_demenageur.id}) }}">show</a>
                    <a href="{{ path('app_demenageurs_crud_edit', {'id': bricoleurs_demenageur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('app_demenageurs_crud_new') }}">Create new</a> #}
{% endblock %}

templates/demenageurs_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Demenageurs{% endblock %}

{% block body %}

    <h2 style="margin-left:30%;margin-top:20px">Add new Demenageur</h2>
    <div style="margin-left:30%; margin-top:20px; width:300px">
    {{ include('demenageurs_crud/_form.html.twig') }}
    
    <a href="{{ path('app_demenageurs_crud_index') }}" class="btn btn-danger" style="width:150px; margin-top:10px; margin-left:80px">back to list</a>

    </div>
{% endblock %}

templates/demenageurs_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demenageurs{% endblock %}

{% block body %}
    <h1>Le Demenageur {{ bricoleurs_demenageur.Name }}</h1>

    <table class="table">
        <tbody>
            {# <tr>
                <th>Id</th>
                <td>{{ bricoleurs_demenageur.id }}</td>
            </tr> #}
            <tr>
                <th>Name</th>
                <td>{{ bricoleurs_demenageur.Name }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ bricoleurs_demenageur.LastName }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ bricoleurs_demenageur.phone }}</td>
            </tr>
            <tr>
                <th>Job</th>
                <td>{{ bricoleurs_demenageur.Job }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{{ path('app_demenageurs_crud_index') }}" class="btn btn-danger" style="width:150px; margin-top:10px; margin-left:80px">back to list</a>
    <a href="{{ path('app_demenageurs_crud_edit', {'id': bricoleurs_demenageur.id}) }}" class="btn btn-primary" style="width:150px; margin-top:10px; margin-left:80px">edit</a>

    {{ include('demenageurs_crud/_delete_form.html.twig') }}
{% endblock %}